### ISSUE TITLE
Logo en haut à gauche ne marche pas

### ISSUE THREAD

**Issue by Jiehong** [saimn/linuxfr-css#6]
Salut,

Le logo de linuxfr.org semble zoomé sur un coin du logo.

Voici le lien du nouveau logo affiché:

![Logo](https://linuxfr.org/images/logos/logo-linuxfr-cadre-ombre-hd.png)

Cependant, voici ce que je vois:

![Capture](http://s22.postimg.org/4fmedfzox/capture.png)

J'ai ce problème sous Firefox 40.0.2 (et avant aussi), sous Windows 7 et Archlinux.

Idem sous IE 9.0, et après m'être bagaré avec Chromium pour ajouter le certificat SSL, je confirme que ça ne marche pas non plus sous Chromium 46.0.

**Comment by saimn** [comment]
Salut,
en effet j'avais remarqué mais pas pris le temps de corriger, maintenant c'est bon ! (C'est juste que le logo est 2x fois plus grand qu'avant, pour les écrans retina).

**Comment by Jiehong** [comment]
Parfait !

Merci :)
